# .github/workflows/deploy-step-function.yml

name: Deploy Step Function

on:
  push:
    paths:
      - 'infra/step_function/**'
      - '.github/workflows/deploy-step-function.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VALIDATOR_CLUSTER: ${{ secrets.VALIDATOR_CLUSTER }}
      VALIDATOR_TASK_DEFINITION: ${{ secrets.VALIDATOR_TASK_DEFINITION }}
      TRANSFORMER_CLUSTER: ${{ secrets.TRANSFORMER_CLUSTER }}
      TRANSFORMER_TASK_DEFINITION: ${{ secrets.TRANSFORMER_TASK_DEFINITION }}
      CLEANUP_LAMBDA_NAME: ${{ secrets.CLEANUP_LAMBDA_NAME }}
      SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
      STEP_FUNCTION_ARN: ${{ secrets.STEP_FUNCTION_ARN }}
      SUBNETS_JSON: ${{ secrets.SUBNETS_JSON }}
      SECURITY_GROUPS_IDS: ${{ secrets.SECURITY_GROUPS_IDS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Step Function ARN
        run: |
          echo "Step Function ARN: $STEP_FUNCTION_ARN"


      - name: Substitute variables in state machine JSON
        run: |
          mkdir -p output
          envsubst < infra/step_function/state_machine.json > output/state_machine_rendered.json

      - name: Print rendered Step Function JSON
        run: cat output/state_machine_rendered.json

      - name: Validate rendered JSON
        run: jq . output/state_machine_rendered.json

      - name: Deploy Step Function
        run: |
          aws stepfunctions update-state-machine \
            --state-machine-arn "$STEP_FUNCTION_ARN" \
            --definition file://output/state_machine_rendered.json \
            --region "$AWS_REGION"
